### ISSUE TITLE
00_TestCasper module breaks due to module purge

### ISSUE THREAD

**Issue by kmpaul** [NCAR/GPU_workshop#4]
In the `00_TestCasper/TestCasper.ipynb` notebook, it calls `qcmd` in the beginning of the notebook, and then calls `qcmd` in cells at the end of the notebook.  However, in the middle of the notebook, there is a `module purge` call that removes `qcmd` from the user's `PATH`.  Hence, the final executable cells in the notebook breaks.

Is it necessary to `module purge`?  Can you just do a targeted `module unload` call?

**Comment by dphow** [comment]
Thanks for reporting this. This issue was resolved by adding back the `ncarenv` module following the `module purge`.
